### ISSUE TITLE
Compiling failed.

### ISSUE THREAD

**Issue by BernardXiong** [RT-Thread/RTGUI#78]
There is no SIZE_MAX in caret.c: 

components/rtgui/widgets/caret.c: In function '_caret_ondraw':
components/rtgui/widgets/caret.c:149:9: error: 'SIZE_MAX' undeclared (first use in this function)
components/rtgui/widgets/caret.c:149:9: note: each undeclared identifier is reported only once for each function it appears in

**Comment by grissiom** [comment]
Please re-open this if you still have this issue.
