### ISSUE TITLE
VS2008+stimu+RTT

### ISSUE THREAD

**Issue by byranc** [RT-Thread/RTGUI#81]
用最新的RTGUI和 rtt 在VS2008里面编译报错
1>d:\rt-thread-f\rt-thread\components\rtgui\common\matrix.c(4) : fatal error C1083: 无法打开包括文件:“stdint.h”: No such file or directory

**Comment by BernardXiong** [comment]
It seems there is no this header file for VS. We can use rt_uint* to replace uint* type.

**Comment by grissiom** [comment]
This should be fixed by f99c7177deceeacc9ca1f1144aebde7149f29c33 . Please re-open this issue if it still bother you. Thanks.
