### ISSUE TITLE
image.bmp  当试图解码损坏的bmp文件时出错，系统试图释放一块未初始化的内存

### ISSUE THREAD

**Issue by bigben-zay** [RT-Thread/RTGUI#82]
bmp = (struct rtgui_image_bmp *)rtgui_malloc(sizeof(struct rtgui_image_bmp));
        if (bmp == RT_NULL)
        {
            break;
        }
//初始化一下这个指针
bmp->pixels = RT_NULL;

//line 470
    if (bmp)
        rtgui_free(bmp->pixels);

**Comment by grissiom** [comment]
解决了，多谢！
